#!/bin/sh

# apt-get update;
apt-get -y install strongswan xl2tpd;

cat > /etc/ipsec.conf <<EOF
config setup
conn %default
  lifetime=1h
  margintime=9m
  rekeyfuzz = 100%
  keyingtries=1
  keyexchange=ikev1
  authby=secret
  ike=aes128-sha1-modp2048!
  esp=aes128-sha1-modp1024!
 
conn myvpn
  keyexchange=ikev1
  #auto=add
  authby=secret
  type=transport
  leftprotoport=17/1701
  rightprotoport=17/1701
  right=77.37.132.73
  auto=route
  dpdaction=restart
EOF

cat > /etc/ipsec.secrets <<EOF
 : PSK OjT7%2fSnh
EOF

chmod 600 /etc/ipsec.secrets



cat > /etc/xl2tpd/xl2tpd.conf <<EOF
[lac myvpn]
lns = 77.37.132.73
ppp debug = yes
pppoptfile = /etc/ppp/options.l2tpd.client
length bit = yes
redial = yes
redial timeout = 10
EOF

cat > /etc/ppp/options.l2tpd.client <<EOF
ipcp-accept-local
ipcp-accept-remote
refuse-eap
require-mschap-v2
noccp
noauth
mtu 1450
mru 1450
nodefaultroute
connect-delay 5000
name ci_cd_l2tp
password Hu298UHs91Lus8i8Sh
remotename myvpn
ipparam myvpn
EOF

chmod 600 /etc/ppp/options.l2tpd.client



echo "done"
