#!/bin/sh

server_ip=$1
psk=$2
login=$3
password=$4

cat > /etc/ipsec.conf <<EOF
config setup
conn %default
  lifetime=1h
  margintime=9m
  rekeyfuzz = 100%
  keyingtries=1
  keyexchange=ikev1
  authby=secret
  ike=aes128-sha1-modp2048!
  esp=aes128-sha1-modp1024!
 
conn myvpn
  keyexchange=ikev1
  #auto=add
  authby=secret
  type=transport
  leftprotoport=17/1701
  rightprotoport=17/1701
  right=$server_ip
  auto=route
  dpdaction=restart
EOF

cat > /etc/ipsec.secrets <<EOF
 : PSK $psk
EOF

chmod 600 /etc/ipsec.secrets



cat > /etc/xl2tpd/xl2tpd.conf <<EOF
[lac myvpn]
lns = $server_ip
ppp debug = yes
pppoptfile = /etc/ppp/options.l2tpd.client
length bit = yes
redial = yes
redial timeout = 10
EOF

cat > /etc/ppp/options.l2tpd.client <<EOF
ipcp-accept-local
ipcp-accept-remote
refuse-eap
require-mschap-v2
noccp
noauth
mtu 1450
mru 1450
nodefaultroute
connect-delay 5000
name $login
password $password
remotename myvpn
ipparam myvpn
EOF

chmod 600 /etc/ppp/options.l2tpd.client



echo "done"
