#!/bin/sh

mkdir -p /var/run/xl2tpd ;
touch /var/run/xl2tpd/l2tp-control ;

service strongswan-starter restart ;
service xl2tpd restart ;

ipsec up myvpn ;

echo "c myvpn" > /var/run/xl2tpd/l2tp-control ;

# ip route
sleep 2

DEFAULT_ROUTE=$(ip route show default | awk '/default/ {print $3}')
PUBLIC_IP=$(wget -qO- http://ipv4.icanhazip.com; echo ;)
echo $DEFAULT_ROUTE;
echo $PUBLIC_IP
#route add $VPN_SERVER_IP gw $DEFAULT_ROUTE
#route add $PUBLIC_IP gw $DEFAULT_ROUTE

until ip -f inet addr show ppp0; do sleep 5; ip a; done
sleep 20
#route add default dev ppp0
